version: '3.9'

services:
  pgdb:
    image: postgres:16.4
    ports:
      - "54320:5432"
    env_file:
      - back/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: unless-stopped
#    networks:
#      - app-network
  nginx:
    build:
      context: ./front
    container_name: nginx
    ports:
      - "80:80"
#    volumes:
#      - ./upload:/upload/
#    networks:
#      - app-network
#  go-back:
#    build: ./back
#    ports:
#      - "8000:8000"
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=youruser
#      - DB_PASSWORD=yourpassword
#      - DB_NAME=yourdb
#      - JWT_SECRET=your-secret-key
#    depends_on:
#      - postgres


volumes:
  pg_data:
#  nginx_data:

#networks:
#  app-network:
#    driver: bridge